### PR TITLE
Makefile: Update Alpine to 3.15.0

### PR DESCRIPTION
**Pull request by hose1021**
```
Linux kernels 5.15 (LTS)
llvm 12
nodejs 16.13 (LTS) / nodejs-current 17.0
postgresql 14
openldap 2.6
ruby 3.0
rust 1.56
openjdk 17
kea 2.0
xorg-server 21.1
GNOME 41
KDE Plasma 5.23 / KDE Applications 21.08 / Plasma Mobile Gear 21.10
Support for disk encryption in installer
Support for out-of-tree kernel modules via AKMS (inspired by DKMS)
Initial support for UEFI Secure Boot on x86_64
```

https://www.alpinelinux.org/posts/Alpine-3.15.0-released.html

### CODE REVIEW

**Review by yuk7 — APPROVED** [review]
Looks good.

**Comment by yuk7** [comment]
Merged.
Thank you for your contributing.

**Comment by hose1021** [comment]
at now it creating ext4 
image

**Comment by yuk7** [comment]
Yeah, WSL2 generates ext4.vhdx for filesystem root.

**Pull request merged**
