### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by 167rgc911**
to latest Alpine 3.17.1 release

### CODE REVIEW

**Comment by phanirithvij** [comment]
Now 3.18.2 exists

**Comment by 167rgc911** [comment]
> Now 3.18.2 exists

i suggest you just fork the yuk's repo and make your own changes locally. i think the dev is busy.

**Comment by yuk7** [comment]
sorry for later...
I'll merge this pr.
thank u for your contribution!

**Review by yuk7 — APPROVED** [review]

**Comment by phanirithvij** [comment]
@yuk7 can you draft a release? The build artifacts get deleted after a few months

**Comment by yuk7** [comment]
I'll create a new release today.

**Pull request merged**
